// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/99-66/go-gin-project-template/controllers"
	"github.com/99-66/go-gin-project-template/repositories"
	"github.com/99-66/go-gin-project-template/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initTodoAPI(db *gorm.DB) controllers.TodoAPI {
	todoRepository := repositories.ProvideTodoRepository(db)
	todoService := services.ProvideTodoService(todoRepository)
	todoAPI := controllers.ProvideTodoAPI(todoService)
	return todoAPI
}
